openapi: 3.0.3
info:
  title: YuiHub API
  version: 0.1.0
paths:
  /health:
    get:
      responses:
        '200':
          description: OK
  /save:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                frontmatter:
                  type: object
                  additionalProperties: true
                body:
                  type: string
      responses:
        '200': { description: Saved }
  /recent:
    get:
      parameters:
        - in: query
          name: n
          schema: { type: integer, default: 20 }
      responses:
        '200': { description: OK }
  /search:
    get:
      parameters:
        - in: query
          name: q
          required: true
          schema: { type: string }
        - in: query
          name: limit
          schema: { type: integer, default: 10 }
      responses:
        '200': { description: OK }
